name: qr_ksa
description: "A new Flutter project."
publish_to: "none" # يمنع النشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  font_awesome_flutter: ^10.8.0
  hugeicons: ^0.0.11
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  file_picker: ^10.2.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  flutter_contacts: ^1.1.9+2
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.9.1
  sign_in_with_apple: ^7.0.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
